model:
  provider: "custom"
  default: "Qwen/qwen-max-latest"
  base_url: ""

display:
  skin: "default"

terminal:
  backend: "local"
  cwd: "."
  timeout: 180
  lifetime_seconds: 300
  docker_mount_cwd_to_workspace: false
  container_cpu: 1
  container_memory: 5120
